MATPLOTLIB_DENYLIST = {
    "show",
    "pause",
    "ginput",
    "connect",
    "waitforbuttonpress",
    "ion",
    "ioff",
}

# 100+ Pyplot functions
MATPLOTLIB_PYPLOT_ALLOWLIST = {
    "figure": {
        "summary": "Create a new figure, or activate an existing figure.",
        "io_pattern": "PURE_CONSTRUCTOR",
        "params": {
            "num": {"type": "integer", "description": "Unique identifier for the figure."},
            "figsize": {"type": "array", "description": "[width, height] in inches"},
            "dpi": {"type": "number", "description": "Dots per inch"},
            "facecolor": {"type": "string", "description": "The figure patch facecolor"},
            "edgecolor": {"type": "string", "description": "The figure patch edge color"},
            "frameon": {
                "type": "boolean",
                "description": "Whether to draw the figure frame",
                "default": True,
            },
            "clear": {
                "type": "boolean",
                "description": "If True and the figure already exists, then it is cleared",
                "default": False,
            },
        },
    },
    "subplots": {
        "summary": "Create a figure and a set of subplots.",
        "io_pattern": "MATPLOTLIB_SUBPLOTS",
        "params": {
            "nrows": {"type": "integer", "default": 1},
            "ncols": {"type": "integer", "default": 1},
            "sharex": {
                "type": "string",
                "description": "Controls sharing of properties among x-axes",
            },
            "sharey": {
                "type": "string",
                "description": "Controls sharing of properties among y-axes",
            },
            "squeeze": {"type": "boolean", "default": True},
            "figsize": {"type": "array", "description": "[width, height] in inches"},
        },
    },
    "close": {"summary": "Close a figure.", "io_pattern": "OBJECTREF_CHAIN"},
    "clf": {"summary": "Clear the current figure.", "io_pattern": "OBJECTREF_CHAIN"},
    "cla": {"summary": "Clear the current axes.", "io_pattern": "OBJECTREF_CHAIN"},
    "gcf": {"summary": "Get the current figure.", "io_pattern": "PURE_CONSTRUCTOR"},
    "gca": {"summary": "Get the current axes.", "io_pattern": "PURE_CONSTRUCTOR"},
    "sca": {"summary": "Set the current axes.", "io_pattern": "OBJECTREF_CHAIN"},
    "subplot": {"summary": "Add a subplot.", "io_pattern": "OBJECTREF_CHAIN"},
    "subplot2grid": {"summary": "Create a subplot at location.", "io_pattern": "OBJECTREF_CHAIN"},
    "subplots_adjust": {"summary": "Adjust subplot layout.", "io_pattern": "OBJECTREF_CHAIN"},
    "title": {"summary": "Set title.", "io_pattern": "OBJECTREF_CHAIN"},
    "xlabel": {"summary": "Set xlabel.", "io_pattern": "OBJECTREF_CHAIN"},
    "ylabel": {"summary": "Set ylabel.", "io_pattern": "OBJECTREF_CHAIN"},
    "xlim": {"summary": "Set xlim.", "io_pattern": "OBJECTREF_CHAIN"},
    "ylim": {"summary": "Set ylim.", "io_pattern": "OBJECTREF_CHAIN"},
    "xticks": {"summary": "Set xticks.", "io_pattern": "OBJECTREF_CHAIN"},
    "yticks": {"summary": "Set yticks.", "io_pattern": "OBJECTREF_CHAIN"},
    "grid": {"summary": "Configure grid.", "io_pattern": "OBJECTREF_CHAIN"},
    "legend": {
        "summary": "Add legend.",
        "io_pattern": "OBJECTREF_CHAIN",
        "params": {
            "loc": {"type": "string", "description": "The location of the legend"},
            "title": {"type": "string", "description": "The legend's title"},
        },
    },
    "colorbar": {
        "summary": "Add colorbar.",
        "io_pattern": "OBJECTREF_CHAIN",
        "params": {
            "mappable": {"type": "object", "description": "The mappable for the colorbar"},
            "ax": {"type": "object", "description": "The axes for the colorbar"},
        },
    },
    "annotate": {"summary": "Add annotation.", "io_pattern": "OBJECTREF_CHAIN"},
    "text": {"summary": "Add text.", "io_pattern": "OBJECTREF_CHAIN"},
    "axhline": {"summary": "Horizontal line.", "io_pattern": "OBJECTREF_CHAIN"},
    "axvline": {"summary": "Vertical line.", "io_pattern": "OBJECTREF_CHAIN"},
    "axhspan": {"summary": "Horizontal span.", "io_pattern": "OBJECTREF_CHAIN"},
    "axvspan": {"summary": "Vertical span.", "io_pattern": "OBJECTREF_CHAIN"},
    "axline": {"summary": "Straight line.", "io_pattern": "OBJECTREF_CHAIN"},
    "hlines": {"summary": "Plot horizontal lines.", "io_pattern": "OBJECTREF_CHAIN"},
    "vlines": {"summary": "Plot vertical lines.", "io_pattern": "OBJECTREF_CHAIN"},
    "plot": {"summary": "Plot lines.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "scatter": {"summary": "Scatter plot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "bar": {"summary": "Bar plot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "barh": {"summary": "Horizontal bar plot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "hist": {"summary": "Histogram.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "hist2d": {"summary": "2D Histogram.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "boxplot": {"summary": "Boxplot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "violinplot": {"summary": "Violin plot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "pie": {"summary": "Pie chart.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "stackplot": {"summary": "Stacked area plot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "stem": {"summary": "Stem plot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "step": {"summary": "Step plot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "fill": {"summary": "Fill polygons.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "fill_between": {"summary": "Fill between.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "fill_betweenx": {"summary": "Fill between x.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "imshow": {"summary": "Display image.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "pcolormesh": {"summary": "Pseudocolor plot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "contour": {"summary": "Contour plot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "contourf": {"summary": "Filled contour.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "quiver": {"summary": "Quiver plot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "streamplot": {"summary": "Stream plot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "autoscale": {"summary": "Autoscale.", "io_pattern": "OBJECTREF_CHAIN"},
    "axis": {"summary": "Set axis properties.", "io_pattern": "OBJECTREF_CHAIN"},
    "box": {"summary": "Axes box on/off.", "io_pattern": "OBJECTREF_CHAIN"},
    "clim": {"summary": "Color limits.", "io_pattern": "OBJECTREF_CHAIN"},
    "errorbar": {"summary": "Error bars.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "hexbin": {"summary": "Hexbin plot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "loglog": {"summary": "Log-log plot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "semilogx": {"summary": "Semilog-x plot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "semilogy": {"summary": "Semilog-y plot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "margins": {"summary": "Set margins.", "io_pattern": "OBJECTREF_CHAIN"},
    "minorticks_on": {"summary": "Minor ticks on.", "io_pattern": "OBJECTREF_CHAIN"},
    "minorticks_off": {"summary": "Minor ticks off.", "io_pattern": "OBJECTREF_CHAIN"},
    "rc": {"summary": "Set rc params.", "io_pattern": "OBJECTREF_CHAIN"},
    "rcdefaults": {"summary": "Reset rc params.", "io_pattern": "OBJECTREF_CHAIN"},
    "set_cmap": {"summary": "Set colormap.", "io_pattern": "OBJECTREF_CHAIN"},
    "tight_layout": {"summary": "Tight layout.", "io_pattern": "OBJECTREF_CHAIN"},
    "suptitle": {"summary": "Figure suptitle.", "io_pattern": "OBJECTREF_CHAIN"},
    "tick_params": {"summary": "Tick params.", "io_pattern": "OBJECTREF_CHAIN"},
    "ticklabel_format": {"summary": "Tick label format.", "io_pattern": "OBJECTREF_CHAIN"},
    # Colormaps (shortcuts)
    "autumn": {"summary": "Set colormap to autumn.", "io_pattern": "OBJECTREF_CHAIN"},
    "bone": {"summary": "Set colormap to bone.", "io_pattern": "OBJECTREF_CHAIN"},
    "cool": {"summary": "Set colormap to cool.", "io_pattern": "OBJECTREF_CHAIN"},
    "copper": {"summary": "Set colormap to copper.", "io_pattern": "OBJECTREF_CHAIN"},
    "flag": {"summary": "Set colormap to flag.", "io_pattern": "OBJECTREF_CHAIN"},
    "gray": {"summary": "Set colormap to gray.", "io_pattern": "OBJECTREF_CHAIN"},
    "hot": {"summary": "Set colormap to hot.", "io_pattern": "OBJECTREF_CHAIN"},
    "hsv": {"summary": "Set colormap to hsv.", "io_pattern": "OBJECTREF_CHAIN"},
    "jet": {"summary": "Set colormap to jet.", "io_pattern": "OBJECTREF_CHAIN"},
    "pink": {"summary": "Set colormap to pink.", "io_pattern": "OBJECTREF_CHAIN"},
    "prism": {"summary": "Set colormap to prism.", "io_pattern": "OBJECTREF_CHAIN"},
    "spring": {"summary": "Set colormap to spring.", "io_pattern": "OBJECTREF_CHAIN"},
    "summer": {"summary": "Set colormap to summer.", "io_pattern": "OBJECTREF_CHAIN"},
    "winter": {"summary": "Set colormap to winter.", "io_pattern": "OBJECTREF_CHAIN"},
    "magma": {"summary": "Set colormap to magma.", "io_pattern": "OBJECTREF_CHAIN"},
    "inferno": {"summary": "Set colormap to inferno.", "io_pattern": "OBJECTREF_CHAIN"},
    "plasma": {"summary": "Set colormap to plasma.", "io_pattern": "OBJECTREF_CHAIN"},
    "viridis": {"summary": "Set colormap to viridis.", "io_pattern": "OBJECTREF_CHAIN"},
    "cividis": {"summary": "Set colormap to cividis.", "io_pattern": "OBJECTREF_CHAIN"},
    # More helpers
    "draw": {"summary": "Redraw figure.", "io_pattern": "OBJECTREF_CHAIN"},
    "draw_if_interactive": {"summary": "Draw if interactive.", "io_pattern": "OBJECTREF_CHAIN"},
    "figaspect": {"summary": "Calculate aspect ratio.", "io_pattern": "PURE_CONSTRUCTOR"},
    "figimage": {"summary": "Add image to figure.", "io_pattern": "OBJECTREF_CHAIN"},
    "figlegend": {"summary": "Add legend to figure.", "io_pattern": "OBJECTREF_CHAIN"},
    "fignum_exists": {"summary": "Check if figure exists.", "io_pattern": "PURE_CONSTRUCTOR"},
    "figtext": {"summary": "Add text to figure.", "io_pattern": "OBJECTREF_CHAIN"},
    "get_fignums": {"summary": "Get open figure numbers.", "io_pattern": "PURE_CONSTRUCTOR"},
    "get_figlabels": {"summary": "Get figure labels.", "io_pattern": "PURE_CONSTRUCTOR"},
    "get_scale_names": {"summary": "Get scale names.", "io_pattern": "PURE_CONSTRUCTOR"},
    "imread": {"summary": "Read image.", "io_pattern": "PURE_CONSTRUCTOR"},
    "imsave": {"summary": "Save image.", "io_pattern": "OBJECTREF_CHAIN"},
    "locator_params": {"summary": "Set locator params.", "io_pattern": "OBJECTREF_CHAIN"},
    "plotting": {"summary": "Plotting module.", "io_pattern": "PURE_CONSTRUCTOR"},
    "rgrids": {"summary": "Set radial grids.", "io_pattern": "OBJECTREF_CHAIN"},
    "thetagrids": {"summary": "Set theta grids.", "io_pattern": "OBJECTREF_CHAIN"},
    "table": {"summary": "Add table.", "io_pattern": "OBJECTREF_CHAIN"},
    "tricontour": {"summary": "Triangular contour.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "tricontourf": {"summary": "Filled triangular contour.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "tripcolor": {"summary": "Triangular pseudocolor.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "triplot": {"summary": "Triangular plot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "xcorr": {"summary": "Cross correlation.", "io_pattern": "MATPLOTLIB_AXES_OP"},
}

# 40+ Figure methods
MATPLOTLIB_FIGURE_ALLOWLIST = {
    "savefig": {
        "summary": "Save the current figure.",
        "io_pattern": "PLOT",
        "params": {
            "format": {
                "type": "string",
                "description": "The file format (e.g. 'png', 'pdf', 'svg')",
            },
            "dpi": {"type": "number", "description": "The resolution in dots per inch"},
            "bbox_inches": {
                "type": "string",
                "description": "Bounding box in inches: 'tight' or None",
            },
            "transparent": {
                "type": "boolean",
                "description": "Whether to make the background transparent",
                "default": False,
            },
        },
    },
    "add_subplot": {"summary": "Add subplot.", "io_pattern": "OBJECTREF_CHAIN"},
    "add_axes": {"summary": "Add axes.", "io_pattern": "OBJECTREF_CHAIN"},
    "clf": {"summary": "Clear figure.", "io_pattern": "OBJECTREF_CHAIN"},
    "clear": {"summary": "Clear figure.", "io_pattern": "OBJECTREF_CHAIN"},
    "tight_layout": {"summary": "Tight layout.", "io_pattern": "OBJECTREF_CHAIN"},
    "suptitle": {"summary": "Figure suptitle.", "io_pattern": "OBJECTREF_CHAIN"},
    "subplots_adjust": {"summary": "Adjust subplots.", "io_pattern": "OBJECTREF_CHAIN"},
    "colorbar": {
        "summary": "Add colorbar.",
        "io_pattern": "OBJECTREF_CHAIN",
        "params": {
            "mappable": {"type": "object", "description": "The mappable for the colorbar"},
            "ax": {"type": "object", "description": "The axes for the colorbar"},
        },
    },
    "legend": {
        "summary": "Add legend.",
        "io_pattern": "OBJECTREF_CHAIN",
        "params": {
            "loc": {"type": "string", "description": "The location of the legend"},
            "title": {"type": "string", "description": "The legend's title"},
        },
    },
    "text": {"summary": "Add text.", "io_pattern": "OBJECTREF_CHAIN"},
    "figimage": {"summary": "Add image.", "io_pattern": "OBJECTREF_CHAIN"},
    "set_size_inches": {"summary": "Set size.", "io_pattern": "OBJECTREF_CHAIN"},
    "get_size_inches": {"summary": "Get size.", "io_pattern": "OBJECTREF_CHAIN"},
    "set_dpi": {"summary": "Set DPI.", "io_pattern": "OBJECTREF_CHAIN"},
    "get_dpi": {"summary": "Get DPI.", "io_pattern": "OBJECTREF_CHAIN"},
    "set_facecolor": {"summary": "Set facecolor.", "io_pattern": "OBJECTREF_CHAIN"},
    "get_facecolor": {"summary": "Get facecolor.", "io_pattern": "OBJECTREF_CHAIN"},
    "set_edgecolor": {"summary": "Set edgecolor.", "io_pattern": "OBJECTREF_CHAIN"},
    "get_edgecolor": {"summary": "Get edgecolor.", "io_pattern": "OBJECTREF_CHAIN"},
    "set_frameon": {"summary": "Set frameon.", "io_pattern": "OBJECTREF_CHAIN"},
    "get_frameon": {"summary": "Get frameon.", "io_pattern": "OBJECTREF_CHAIN"},
    "align_labels": {"summary": "Align labels.", "io_pattern": "OBJECTREF_CHAIN"},
    "align_xlabels": {"summary": "Align xlabels.", "io_pattern": "OBJECTREF_CHAIN"},
    "align_ylabels": {"summary": "Align ylabels.", "io_pattern": "OBJECTREF_CHAIN"},
    "autofmt_xdate": {"summary": "Auto format date labels.", "io_pattern": "OBJECTREF_CHAIN"},
    "add_gridspec": {"summary": "Add gridspec.", "io_pattern": "PURE_CONSTRUCTOR"},
    "add_subfigure": {"summary": "Add subfigure.", "io_pattern": "PURE_CONSTRUCTOR"},
    "execute_constrained_layout": {
        "summary": "Execute constrained layout.",
        "io_pattern": "OBJECTREF_CHAIN",
    },
    "get_axes": {"summary": "Get axes.", "io_pattern": "PURE_CONSTRUCTOR"},
    "get_children": {"summary": "Get children.", "io_pattern": "PURE_CONSTRUCTOR"},
    "get_constrained_layout": {
        "summary": "Get constrained layout.",
        "io_pattern": "PURE_CONSTRUCTOR",
    },
    "get_tight_layout": {"summary": "Get tight layout.", "io_pattern": "PURE_CONSTRUCTOR"},
    "set_constrained_layout": {
        "summary": "Set constrained layout.",
        "io_pattern": "OBJECTREF_CHAIN",
    },
    "set_tight_layout": {"summary": "Set tight layout.", "io_pattern": "OBJECTREF_CHAIN"},
    "subfigures": {"summary": "Add subfigures.", "io_pattern": "PURE_CONSTRUCTOR"},
}

# 60+ Axes methods
MATPLOTLIB_AXES_ALLOWLIST = {
    "plot": {
        "summary": "Plot y versus x as lines and/or markers.",
        "io_pattern": "MATPLOTLIB_AXES_OP",
        "params": {
            "x": {"type": "array", "description": "x-coordinates"},
            "y": {"type": "array", "description": "y-coordinates"},
            "fmt": {"type": "string", "description": "Format string (e.g. 'ro' for red circles)"},
            "label": {"type": "string", "description": "Label for legend"},
            "linewidth": {"type": "number", "description": "Line width"},
            "color": {"type": "string", "description": "Line color"},
            "marker": {"type": "string", "description": "Marker style"},
        },
    },
    "scatter": {
        "summary": "A scatter plot of y vs. x with varying marker size and/or color.",
        "io_pattern": "MATPLOTLIB_AXES_OP",
        "params": {
            "x": {"type": "array", "description": "x-coordinates"},
            "y": {"type": "array", "description": "y-coordinates"},
            "s": {"type": "number", "description": "Marker size"},
            "c": {"type": "string", "description": "Marker color"},
            "marker": {"type": "string", "description": "Marker style"},
            "cmap": {"type": "string", "description": "Colormap"},
            "alpha": {"type": "number", "description": "Transparency"},
        },
    },
    "imshow": {
        "summary": "Display data as an image, i.e., on a 2D regular raster.",
        "io_pattern": "MATPLOTLIB_AXES_OP",
        "params": {
            "X": {"type": "object", "description": "Image data (BioImageRef or array)"},
            "cmap": {"type": "string", "description": "Colormap"},
            "aspect": {"type": "string", "description": "Aspect ratio"},
            "interpolation": {"type": "string", "description": "Interpolation method"},
            "alpha": {"type": "number", "description": "Transparency"},
            "vmin": {"type": "number", "description": "Minimum data value"},
            "vmax": {"type": "number", "description": "Maximum data value"},
            "origin": {
                "type": "string",
                "description": "Place the [0, 0] index of the array in the upper or lower left",
            },
            "max_display_size": {
                "type": "integer",
                "description": "Maximum size for display downsampling",
            },
        },
    },
    "hist": {
        "summary": "Compute and plot a histogram.",
        "io_pattern": "MATPLOTLIB_AXES_OP",
        "params": {
            "x": {"type": "array", "description": "Input values"},
            "bins": {"type": "integer", "description": "Number of histogram bins"},
            "range": {"type": "array", "description": "The lower and upper range of the bins"},
            "density": {
                "type": "boolean",
                "description": "Whether to normalize the histogram",
                "default": False,
            },
            "color": {"type": "string", "description": "Bar color"},
            "alpha": {"type": "number", "description": "Transparency"},
        },
    },
    "bar": {"summary": "Make a bar plot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "barh": {"summary": "Make a horizontal bar plot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "boxplot": {
        "summary": "Make a box and whisker plot.",
        "io_pattern": "MATPLOTLIB_AXES_OP",
        "params": {
            "x": {"type": "object", "description": "The input data (array or column name)"},
            "positions": {
                "type": "object",
                "description": "The positions of the boxes (array or column name for grouping)",
            },
            "labels": {"type": "array", "description": "Labels for each box"},
            "vert": {
                "type": "boolean",
                "default": True,
                "description": "If True, makes vertical boxes",
            },
            "patch_artist": {
                "type": "boolean",
                "default": False,
                "description": "If True, fills boxes with color",
            },
            "widths": {"type": "object", "description": "The widths of the boxes"},
        },
    },
    "violinplot": {
        "summary": "Make a violin plot.",
        "io_pattern": "MATPLOTLIB_AXES_OP",
        "params": {
            "dataset": {"type": "object", "description": "The input data (array or column name)"},
            "positions": {
                "type": "object",
                "description": "The positions of the violins (array or column name for grouping)",
            },
            "labels": {
                "type": "array",
                "description": "Labels for each violin (used when grouping)",
            },
            "vert": {
                "type": "boolean",
                "default": True,
                "description": "If True, makes vertical violins",
            },
            "widths": {"type": "object", "description": "The widths of each violin"},
            "showmeans": {
                "type": "boolean",
                "default": False,
                "description": "Whether to show the mean",
            },
            "showextrema": {
                "type": "boolean",
                "default": True,
                "description": "Whether to show the extrema",
            },
            "showmedians": {
                "type": "boolean",
                "default": False,
                "description": "Whether to show the median",
            },
        },
    },
    "pie": {"summary": "Plot a pie chart.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "errorbar": {
        "summary": "Plot y versus x with attached errorbars.",
        "io_pattern": "MATPLOTLIB_AXES_OP",
    },
    "step": {"summary": "Make a step plot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "stem": {"summary": "Create a stem plot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "stackplot": {"summary": "Draw a stacked area plot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "fill_between": {
        "summary": "Fill the area between two horizontal curves.",
        "io_pattern": "MATPLOTLIB_AXES_OP",
    },
    "fill_betweenx": {
        "summary": "Fill the area between two vertical curves.",
        "io_pattern": "MATPLOTLIB_AXES_OP",
    },
    "set_title": {
        "summary": "Set a title for the Axes.",
        "io_pattern": "OBJECTREF_CHAIN",
        "params": {
            "label": {"type": "string", "description": "The title text"},
            "fontdict": {
                "type": "object",
                "description": "A dictionary controlling the appearance of the title text",
            },
            "loc": {
                "type": "string",
                "description": "Which title to set: 'center', 'left', 'right'",
            },
        },
    },
    "set_xlabel": {
        "summary": "Set the label for the x-axis.",
        "io_pattern": "OBJECTREF_CHAIN",
        "params": {
            "xlabel": {"type": "string", "description": "The label text"},
        },
    },
    "set_ylabel": {
        "summary": "Set the label for the y-axis.",
        "io_pattern": "OBJECTREF_CHAIN",
        "params": {
            "ylabel": {"type": "string", "description": "The label text"},
        },
    },
    "set_xlim": {
        "summary": "Set the x-axis view limits.",
        "io_pattern": "OBJECTREF_CHAIN",
        "params": {
            "left": {"type": "number", "description": "The left xlim"},
            "right": {"type": "number", "description": "The right xlim"},
        },
    },
    "set_ylim": {
        "summary": "Set the y-axis view limits.",
        "io_pattern": "OBJECTREF_CHAIN",
        "params": {
            "bottom": {"type": "number", "description": "The bottom ylim"},
            "top": {"type": "number", "description": "The top ylim"},
        },
    },
    "set_xticks": {"summary": "Set the x-axis tick locations.", "io_pattern": "OBJECTREF_CHAIN"},
    "set_yticks": {"summary": "Set the y-axis tick locations.", "io_pattern": "OBJECTREF_CHAIN"},
    "set_xticklabels": {
        "summary": "Set the x-axis labels with list of string labels.",
        "io_pattern": "OBJECTREF_CHAIN",
    },
    "set_yticklabels": {
        "summary": "Set the y-axis labels with list of string labels.",
        "io_pattern": "OBJECTREF_CHAIN",
    },
    "set_xscale": {"summary": "Set the x-axis scale.", "io_pattern": "OBJECTREF_CHAIN"},
    "set_yscale": {"summary": "Set the y-axis scale.", "io_pattern": "OBJECTREF_CHAIN"},
    "grid": {
        "summary": "Configure the grid lines.",
        "io_pattern": "OBJECTREF_CHAIN",
        "params": {
            "visible": {"type": "boolean", "description": "Whether to show the grid lines"},
            "which": {
                "type": "string",
                "description": "The grid lines to apply the changes on: 'major', 'minor', 'both'",
            },
            "axis": {
                "type": "string",
                "description": "The axis to apply the changes on: 'both', 'x', 'y'",
            },
        },
    },
    "legend": {
        "summary": "Place a legend on the axes.",
        "io_pattern": "OBJECTREF_CHAIN",
        "params": {
            "loc": {"type": "string", "description": "The location of the legend"},
            "title": {"type": "string", "description": "The legend's title"},
        },
    },
    "tick_params": {
        "summary": "Change the appearance of ticks, tick labels, and gridlines.",
        "io_pattern": "OBJECTREF_CHAIN",
        "params": {
            "axis": {
                "type": "string",
                "description": "The axis to apply the changes on: 'both', 'x', 'y'",
            },
            "labelsize": {"type": "number", "description": "Tick label font size in points"},
            "labelcolor": {"type": "string", "description": "Tick label color"},
            "direction": {"type": "string", "description": "Puts ticks 'in', 'out', or 'inout'"},
        },
    },
    "text": {
        "summary": "Add text to the axes.",
        "io_pattern": "OBJECTREF_CHAIN",
        "params": {
            "x": {"type": "number", "description": "The x position of the text"},
            "y": {"type": "number", "description": "The y position of the text"},
            "s": {"type": "string", "description": "The text"},
            "fontsize": {"type": "number", "description": "The font size"},
            "color": {"type": "string", "description": "The text color"},
        },
    },
    "annotate": {
        "summary": "Annotate the point xy with text s.",
        "io_pattern": "OBJECTREF_CHAIN",
        "params": {
            "text": {"type": "string", "description": "The text of the annotation"},
            "xy": {"type": "array", "description": "(x, y) point to annotate"},
            "xytext": {"type": "array", "description": "(x, y) to place the text"},
            "arrowprops": {"type": "object", "description": "Properties used to draw an arrow"},
        },
    },
    "colorbar": {
        "summary": "Add a colorbar to a plot.",
        "io_pattern": "OBJECTREF_CHAIN",
        "params": {
            "mappable": {
                "type": "object",
                "description": "The mappable to which the colorbar applies",
            },
            "ax": {"type": "object", "description": "The axes to use for the colorbar"},
            "label": {"type": "string", "description": "The label on the colorbar's long axis"},
        },
    },
    "cla": {"summary": "Clear axes.", "io_pattern": "OBJECTREF_CHAIN"},
    "clear": {"summary": "Clear axes.", "io_pattern": "OBJECTREF_CHAIN"},
    "set_axis_off": {"summary": "Axis off.", "io_pattern": "OBJECTREF_CHAIN"},
    "set_axis_on": {"summary": "Axis on.", "io_pattern": "OBJECTREF_CHAIN"},
    "set_frame_on": {"summary": "Frame on.", "io_pattern": "OBJECTREF_CHAIN"},
    "set_facecolor": {"summary": "Facecolor.", "io_pattern": "OBJECTREF_CHAIN"},
    "set_aspect": {"summary": "Aspect.", "io_pattern": "OBJECTREF_CHAIN"},
    "autoscale": {"summary": "Autoscale.", "io_pattern": "OBJECTREF_CHAIN"},
    "invert_xaxis": {"summary": "Invert x.", "io_pattern": "OBJECTREF_CHAIN"},
    "invert_yaxis": {"summary": "Invert y.", "io_pattern": "OBJECTREF_CHAIN"},
    "axhline": {"summary": "Horizontal line.", "io_pattern": "OBJECTREF_CHAIN"},
    "axvline": {"summary": "Vertical line.", "io_pattern": "OBJECTREF_CHAIN"},
    "axhspan": {"summary": "Horizontal span.", "io_pattern": "OBJECTREF_CHAIN"},
    "axvspan": {"summary": "Vertical span.", "io_pattern": "OBJECTREF_CHAIN"},
    "axline": {"summary": "Straight line.", "io_pattern": "OBJECTREF_CHAIN"},
    "contour": {"summary": "Contour plot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "contourf": {"summary": "Filled contour.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "pcolor": {"summary": "Pseudocolor.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "pcolormesh": {"summary": "Pseudocolor mesh.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "quiver": {"summary": "Quiver plot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "streamplot": {"summary": "Stream plot.", "io_pattern": "MATPLOTLIB_AXES_OP"},
    "add_patch": {
        "summary": "Add a Patch to the Axes; return the patch.",
        "io_pattern": "MATPLOTLIB_AXES_OP",
        "params": {
            "p": {"type": "object", "description": "The patch to add"},
        },
    },
    "add_table": {"summary": "Add table.", "io_pattern": "OBJECTREF_CHAIN"},
    "set_position": {"summary": "Set axes position.", "io_pattern": "OBJECTREF_CHAIN"},
    "set_anchor": {"summary": "Set anchor.", "io_pattern": "OBJECTREF_CHAIN"},
    "set_adjustable": {"summary": "Set adjustable.", "io_pattern": "OBJECTREF_CHAIN"},
    "set_axisbelow": {"summary": "Set axis below.", "io_pattern": "OBJECTREF_CHAIN"},
    "set_box_aspect": {"summary": "Set box aspect.", "io_pattern": "OBJECTREF_CHAIN"},
    "set_prop_cycle": {"summary": "Set prop cycle.", "io_pattern": "OBJECTREF_CHAIN"},
    "set_rasterized": {"summary": "Set rasterized.", "io_pattern": "OBJECTREF_CHAIN"},
    "set_visible": {"summary": "Set visible.", "io_pattern": "OBJECTREF_CHAIN"},
    "set_zorder": {"summary": "Set zorder.", "io_pattern": "OBJECTREF_CHAIN"},
    "twinx": {"summary": "Create twin x axes.", "io_pattern": "PURE_CONSTRUCTOR"},
    "twiny": {"summary": "Create twin y axes.", "io_pattern": "PURE_CONSTRUCTOR"},
    "secondary_xaxis": {"summary": "Secondary x axis.", "io_pattern": "PURE_CONSTRUCTOR"},
    "secondary_yaxis": {"summary": "Secondary y axis.", "io_pattern": "PURE_CONSTRUCTOR"},
}

# 13 Patches
MATPLOTLIB_PATCHES_ALLOWLIST = {
    "Arc": {"summary": "Elliptical arc.", "io_pattern": "PURE_CONSTRUCTOR"},
    "Arrow": {"summary": "An arrow patch.", "io_pattern": "PURE_CONSTRUCTOR"},
    "Circle": {
        "summary": "A circle patch.",
        "io_pattern": "PURE_CONSTRUCTOR",
        "params": {
            "xy": {"type": "array", "description": "(x, y) center of the circle"},
            "radius": {"type": "number", "description": "Radius of the circle"},
            "color": {"type": "string", "description": "Patch color"},
            "fill": {
                "type": "boolean",
                "description": "Whether to fill the circle",
                "default": True,
            },
            "alpha": {"type": "number", "description": "Transparency"},
        },
    },
    "Ellipse": {"summary": "An elliptical patch.", "io_pattern": "PURE_CONSTRUCTOR"},
    "FancyArrow": {"summary": "Fancy arrow.", "io_pattern": "PURE_CONSTRUCTOR"},
    "FancyArrowPatch": {"summary": "Fancy arrow patch.", "io_pattern": "PURE_CONSTRUCTOR"},
    "FancyBboxPatch": {"summary": "Fancy box patch.", "io_pattern": "PURE_CONSTRUCTOR"},
    "PathPatch": {"summary": "Path patch.", "io_pattern": "PURE_CONSTRUCTOR"},
    "Polygon": {"summary": "Polygon patch.", "io_pattern": "PURE_CONSTRUCTOR"},
    "Rectangle": {
        "summary": "A rectangle patch.",
        "io_pattern": "PURE_CONSTRUCTOR",
        "params": {
            "xy": {"type": "array", "description": "(x, y) lower-left corner"},
            "width": {"type": "number", "description": "Rectangle width"},
            "height": {"type": "number", "description": "Rectangle height"},
            "angle": {"type": "number", "description": "Rotation angle in degrees"},
            "color": {"type": "string", "description": "Patch color"},
            "fill": {
                "type": "boolean",
                "description": "Whether to fill the rectangle",
                "default": True,
            },
        },
    },
    "RegularPolygon": {"summary": "Regular polygon patch.", "io_pattern": "PURE_CONSTRUCTOR"},
    "Shadow": {"summary": "Shadow patch.", "io_pattern": "PURE_CONSTRUCTOR"},
    "Wedge": {"summary": "Wedge patch.", "io_pattern": "PURE_CONSTRUCTOR"},
}
